name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        uses: appleboy/scp-action@master
        with:
          host: seu_servidor_ip
          username: seu_usuário
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: ./dist/
          target: /caminho/para/destino/
