name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Install SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.REALESTATEAPPSSHSECRETKEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan 193.46.198.117 >> ~/.ssh/known_hosts

      - name: Deploy to server
        run: |
          ssh -i ~/.ssh/id_rsa root@193.46.198.117 "mkdir -p /root/applications"
          scp -i ~/.ssh/id_rsa -r ./dist/ root@193.46.198.117:/root/applications
