name: CI/CD

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Deploy to server
        run: |
          ssh-keyscan 193.46.198.117 >> /root/.ssh/authorized_keys
          ssh -i ${{ secrets.realestateappsshsecretkey }} user@193.46.198.117 "mkdir -p /home/user/applications"
          scp -i ${{ secrets.realestateappsshsecretkey }} -r ./dist/ user@193.46.198.117:/home/user/applications